<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>AdvancedK9.LSPDFRBridge</AssemblyName>
    <RootNamespace>AdvancedK9.LSPDFRBridge</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <BaseIntermediateOutputPath>obj\LSPDFRBridge\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Bridge/BridgeEntryPoint.cs" />
    <Compile Include="Bridge/Properties/AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="RagePluginHook" Version="1.124.0" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
