using System;
using System.Collections.Generic;
using System.Linq;

namespace AdvancedK9
{
    internal static class Localization
    {
        private sealed class LanguagePack
        {
            public string Code, Name;
            public readonly Dictionary<string,string> Text = new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);
            public readonly Dictionary<K9Command,string[]> Commands = new Dictionary<K9Command,string[]>();
            public string[] WakeWords = new string[0];
        }

        private static readonly string[] Order={"en","es","fr","zh","pt","ru","th","tr","vi","de","cs","it","ja","pl"};
        private static readonly Dictionary<string,LanguagePack> Packs=new Dictionary<string,LanguagePack>(StringComparer.OrdinalIgnoreCase);
        private static LanguagePack _current;

        static Localization()
        {
            Add("en","English","k9|k 9|k nine|kay nine|canine",null,null);
            Add("es","Español","k9|canino|perro",MenuEs,CommandsEs);
            Add("fr","Français","k9|canin|chien",MenuFr,CommandsFr);
            Add("zh","中文","k9|警犬|狗",MenuZh,CommandsZh);
            Add("pt","Português","k9|canino|cão|cachorro",MenuPt,CommandsPt);
            Add("ru","Русский","k9|служебная собака|собака",MenuRu,CommandsRu);
            Add("th","ไทย","k9|สุนัขตำรวจ|สุนัข",MenuTh,CommandsTh);
            Add("tr","Türkçe","k9|polis köpeği|köpek",MenuTr,CommandsTr);
            Add("vi","Tiếng Việt","k9|chó nghiệp vụ|chó",MenuVi,CommandsVi);
            Add("de","Deutsch","k9|diensthund|hund",MenuDe,CommandsDe);
            Add("cs","Čeština","k9|služební pes|pes",MenuCs,CommandsCs);
            Add("it","Italiano","k9|cinofilo|cane",MenuIt,CommandsIt);
            Add("ja","日本語","k9|警察犬|犬",MenuJa,CommandsJa);
            Add("pl","Polski","k9|pies służbowy|pies",MenuPl,CommandsPl);
            SetLanguage("en");
        }

        public static IEnumerable<string> SupportedLanguages=>Order.Select(x=>Packs[x].Name+" ("+x+")");
        public static string Code=>_current.Code;
        public static string LanguageName=>_current.Name;
        public static string NormalizeCode(string value)
        {
            if(string.IsNullOrWhiteSpace(value))return "en";
            string code=value.Trim().Replace('_','-').ToLowerInvariant();
            if(code.StartsWith("zh"))return "zh";
            code=code.Split('-')[0];return Packs.ContainsKey(code)?code:"en";
        }
        public static void SetLanguage(string code){_current=Packs[NormalizeCode(code)];}
        public static string NextLanguage(int delta)
        {
            int index=Array.IndexOf(Order,_current.Code);index=(index+(delta<0?-1:1)+Order.Length)%Order.Length;SetLanguage(Order[index]);return _current.Code;
        }
        public static string T(string english)
        {
            if(_current==null||_current.Code=="en"||string.IsNullOrEmpty(english))return english;
            string translated;return _current.Text.TryGetValue(english,out translated)?translated:english;
        }
        public static string CommandLabel(K9Command command,string english)
        {
            string[] values;if(_current!=null&&_current.Commands.TryGetValue(command,out values)&&values.Length>0)return values[0];return english;
        }
        public static IEnumerable<string> CommandPhrases(K9Command command)
        {
            string[] values;return _current!=null&&_current.Commands.TryGetValue(command,out values)?values:Enumerable.Empty<string>();
        }
        public static IEnumerable<string> WakeWords=>_current==null?Enumerable.Empty<string>():_current.WakeWords;
        public static string VoicePromptLanguage=>_current==null?"English":_current.Name;

        private static void Add(string code,string name,string wakes,string menu,string commands)
        {
            var pack=new LanguagePack{Code=code,Name=name,WakeWords=Split(wakes)};
            foreach(string row in SplitRows(menu)){int p=row.IndexOf('=');if(p>0)pack.Text[row.Substring(0,p).Trim()]=row.Substring(p+1).Trim();}
            foreach(string row in SplitRows(commands)){int p=row.IndexOf('=');K9Command command;if(p>0&&Enum.TryParse(row.Substring(0,p).Trim(),true,out command))pack.Commands[command]=Split(row.Substring(p+1));}
            Packs[code]=pack;
        }
        private static string[] Split(string value)=>string.IsNullOrWhiteSpace(value)?new string[0]:value.Split('|').Select(x=>x.Trim()).Where(x=>x.Length>0).ToArray();
        private static IEnumerable<string> SplitRows(string value)=>string.IsNullOrWhiteSpace(value)?Enumerable.Empty<string>():value.Split(new[]{'\n'},StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Trim()).Where(x=>x.Length>0&&!x.StartsWith("#"));

        // Menu packs intentionally use stable English keys. Missing optional text falls
        // back to English, so a community translation can never break menu operation.
        private const string MenuEs="Commands=Comandos\nPartner Control=Control del compañero\nSearch & Detection=Búsqueda y detección\nTracking & Scent=Rastreo y olor\nTactical Deployment=Despliegue táctico\nVehicle & Equipment=Vehículo y equipo\nCare & Medical=Cuidados y medicina\nTraining & Certifications=Entrenamiento y certificaciones\nDeploy / Dismiss=Desplegar / retirar\nBack to Command Categories=Volver a categorías\nIdentity & Appearance=Identidad y apariencia\nHUD & Display=HUD y pantalla\nKennel Location Editor=Editor de perreras\nVehicle Seat Configuration=Configuración del asiento\nProfile, Health & Certifications=Perfil, salud y certificaciones\nLanguage=Idioma\nAppearance=Apariencia\nEdit name=Editar nombre\nBreed/model=Raza/modelo\nSkin/coat=Piel/pelaje\nEquipment/vest=Equipo/chaleco\nVest texture=Textura del chaleco\nBack to K9 Profile=Volver al perfil K9\nKennel Locations=Ubicaciones de perreras\nSave for this vehicle model=Guardar para este vehículo\nReset to global defaults=Restablecer valores globales";
        private const string MenuFr="Commands=Commandes\nPartner Control=Contrôle du partenaire\nSearch & Detection=Recherche et détection\nTracking & Scent=Pistage et odeur\nTactical Deployment=Déploiement tactique\nVehicle & Equipment=Véhicule et équipement\nCare & Medical=Soins et santé\nTraining & Certifications=Entraînement et certifications\nDeploy / Dismiss=Déployer / retirer\nBack to Command Categories=Retour aux catégories\nIdentity & Appearance=Identité et apparence\nHUD & Display=HUD et affichage\nKennel Location Editor=Éditeur des chenils\nVehicle Seat Configuration=Configuration du siège\nProfile, Health & Certifications=Profil, santé et certifications\nLanguage=Langue\nAppearance=Apparence\nEdit name=Modifier le nom\nBreed/model=Race/modèle\nSkin/coat=Peau/robe\nEquipment/vest=Équipement/gilet\nVest texture=Texture du gilet\nBack to K9 Profile=Retour au profil K9\nKennel Locations=Emplacements des chenils\nSave for this vehicle model=Enregistrer pour ce véhicule\nReset to global defaults=Réinitialiser les valeurs globales";
        private const string MenuZh="Commands=指令\nPartner Control=伙伴控制\nSearch & Detection=搜索与探测\nTracking & Scent=追踪与气味\nTactical Deployment=战术部署\nVehicle & Equipment=车辆与装备\nCare & Medical=护理与医疗\nTraining & Certifications=训练与认证\nDeploy / Dismiss=部署 / 收回\nBack to Command Categories=返回指令分类\nIdentity & Appearance=身份与外观\nHUD & Display=HUD与显示\nKennel Location Editor=犬舍位置编辑\nVehicle Seat Configuration=车辆座位设置\nProfile, Health & Certifications=档案、健康与认证\nLanguage=语言\nAppearance=外观\nEdit name=修改名字\nBreed/model=品种/模型\nSkin/coat=皮肤/毛色\nEquipment/vest=装备/背心\nVest texture=背心纹理\nBack to K9 Profile=返回K9档案\nKennel Locations=犬舍位置\nSave for this vehicle model=为此车型保存\nReset to global defaults=恢复全局默认值";
        private const string MenuPt="Commands=Comandos\nPartner Control=Controle do parceiro\nSearch & Detection=Busca e detecção\nTracking & Scent=Rastreamento e odor\nTactical Deployment=Emprego tático\nVehicle & Equipment=Veículo e equipamento\nCare & Medical=Cuidados e saúde\nTraining & Certifications=Treinamento e certificações\nDeploy / Dismiss=Mobilizar / dispensar\nBack to Command Categories=Voltar às categorias\nIdentity & Appearance=Identidade e aparência\nHUD & Display=HUD e tela\nKennel Location Editor=Editor de canis\nVehicle Seat Configuration=Configuração do assento\nProfile, Health & Certifications=Perfil, saúde e certificações\nLanguage=Idioma\nAppearance=Aparência\nEdit name=Editar nome\nBreed/model=Raça/modelo\nSkin/coat=Pele/pelagem\nEquipment/vest=Equipamento/colete\nVest texture=Textura do colete\nBack to K9 Profile=Voltar ao perfil K9\nKennel Locations=Locais dos canis\nSave for this vehicle model=Salvar para este veículo\nReset to global defaults=Restaurar padrões globais";
        private const string MenuRu="Commands=Команды\nPartner Control=Управление напарником\nSearch & Detection=Поиск и обнаружение\nTracking & Scent=След и запах\nTactical Deployment=Тактическое применение\nVehicle & Equipment=Транспорт и снаряжение\nCare & Medical=Уход и медицина\nTraining & Certifications=Обучение и сертификаты\nDeploy / Dismiss=Вывести / убрать\nBack to Command Categories=Назад к категориям\nIdentity & Appearance=Профиль и внешний вид\nHUD & Display=HUD и экран\nKennel Location Editor=Редактор питомников\nVehicle Seat Configuration=Настройка места в машине\nProfile, Health & Certifications=Профиль, здоровье и сертификаты\nLanguage=Язык\nAppearance=Внешний вид\nEdit name=Изменить имя\nBreed/model=Порода/модель\nSkin/coat=Окрас\nEquipment/vest=Снаряжение/жилет\nVest texture=Текстура жилета\nBack to K9 Profile=Назад к профилю K9\nKennel Locations=Расположение питомников\nSave for this vehicle model=Сохранить для этой модели\nReset to global defaults=Сбросить общие настройки";
        private const string MenuTh="Commands=คำสั่ง\nPartner Control=ควบคุมคู่หู\nSearch & Detection=ค้นหาและตรวจจับ\nTracking & Scent=ติดตามกลิ่น\nTactical Deployment=ปฏิบัติการยุทธวิธี\nVehicle & Equipment=ยานพาหนะและอุปกรณ์\nCare & Medical=ดูแลและการแพทย์\nTraining & Certifications=ฝึกและใบรับรอง\nDeploy / Dismiss=นำออก / เก็บ\nBack to Command Categories=กลับไปหมวดคำสั่ง\nIdentity & Appearance=ข้อมูลและรูปลักษณ์\nHUD & Display=HUD และจอแสดงผล\nKennel Location Editor=แก้ไขตำแหน่งคอก\nVehicle Seat Configuration=ตั้งค่าที่นั่งรถ\nProfile, Health & Certifications=ข้อมูล สุขภาพ และใบรับรอง\nLanguage=ภาษา\nAppearance=รูปลักษณ์\nEdit name=แก้ไขชื่อ\nBreed/model=สายพันธุ์/โมเดล\nSkin/coat=ผิว/สีขน\nEquipment/vest=อุปกรณ์/เสื้อกั๊ก\nVest texture=ลายเสื้อกั๊ก\nBack to K9 Profile=กลับไปโปรไฟล์ K9\nKennel Locations=ตำแหน่งคอก\nSave for this vehicle model=บันทึกสำหรับรถรุ่นนี้\nReset to global defaults=คืนค่าเริ่มต้น";
        private const string MenuTr="Commands=Komutlar\nPartner Control=Partner kontrolü\nSearch & Detection=Arama ve tespit\nTracking & Scent=Takip ve koku\nTactical Deployment=Taktik görev\nVehicle & Equipment=Araç ve ekipman\nCare & Medical=Bakım ve sağlık\nTraining & Certifications=Eğitim ve sertifikalar\nDeploy / Dismiss=Çıkar / görevden al\nBack to Command Categories=Komut kategorilerine dön\nIdentity & Appearance=Kimlik ve görünüm\nHUD & Display=HUD ve ekran\nKennel Location Editor=Kulübe konumu düzenleyici\nVehicle Seat Configuration=Araç koltuğu ayarı\nProfile, Health & Certifications=Profil, sağlık ve sertifikalar\nLanguage=Dil\nAppearance=Görünüm\nEdit name=Adı düzenle\nBreed/model=Irk/model\nSkin/coat=Deri/tüy\nEquipment/vest=Ekipman/yelek\nVest texture=Yelek dokusu\nBack to K9 Profile=K9 profiline dön\nKennel Locations=Kulübe konumları\nSave for this vehicle model=Bu araç modeli için kaydet\nReset to global defaults=Genel varsayılanlara sıfırla";
        private const string MenuVi="Commands=Lệnh\nPartner Control=Điều khiển đồng đội\nSearch & Detection=Tìm kiếm và phát hiện\nTracking & Scent=Theo dấu và mùi\nTactical Deployment=Triển khai chiến thuật\nVehicle & Equipment=Phương tiện và thiết bị\nCare & Medical=Chăm sóc và y tế\nTraining & Certifications=Huấn luyện và chứng nhận\nDeploy / Dismiss=Triển khai / cho nghỉ\nBack to Command Categories=Trở lại nhóm lệnh\nIdentity & Appearance=Thông tin và ngoại hình\nHUD & Display=HUD và hiển thị\nKennel Location Editor=Chỉnh vị trí chuồng\nVehicle Seat Configuration=Cấu hình ghế xe\nProfile, Health & Certifications=Hồ sơ, sức khỏe và chứng nhận\nLanguage=Ngôn ngữ\nAppearance=Ngoại hình\nEdit name=Sửa tên\nBreed/model=Giống/mô hình\nSkin/coat=Da/lông\nEquipment/vest=Thiết bị/áo\nVest texture=Họa tiết áo\nBack to K9 Profile=Trở lại hồ sơ K9\nKennel Locations=Vị trí chuồng\nSave for this vehicle model=Lưu cho mẫu xe này\nReset to global defaults=Đặt lại mặc định chung";
        private const string MenuDe="Commands=Befehle\nPartner Control=Partnersteuerung\nSearch & Detection=Suche und Erkennung\nTracking & Scent=Fährte und Geruch\nTactical Deployment=Taktischer Einsatz\nVehicle & Equipment=Fahrzeug und Ausrüstung\nCare & Medical=Pflege und Medizin\nTraining & Certifications=Training und Zertifikate\nDeploy / Dismiss=Einsetzen / zurückrufen\nBack to Command Categories=Zurück zu Befehlskategorien\nIdentity & Appearance=Identität und Aussehen\nHUD & Display=HUD und Anzeige\nKennel Location Editor=Zwingerposition bearbeiten\nVehicle Seat Configuration=Fahrzeugsitz konfigurieren\nProfile, Health & Certifications=Profil, Gesundheit und Zertifikate\nLanguage=Sprache\nAppearance=Aussehen\nEdit name=Name ändern\nBreed/model=Rasse/Modell\nSkin/coat=Haut/Fell\nEquipment/vest=Ausrüstung/Weste\nVest texture=Westentextur\nBack to K9 Profile=Zurück zum K9-Profil\nKennel Locations=Zwingerstandorte\nSave for this vehicle model=Für dieses Fahrzeug speichern\nReset to global defaults=Globale Standardwerte";
        private const string MenuCs="Commands=Povely\nPartner Control=Ovládání partnera\nSearch & Detection=Hledání a detekce\nTracking & Scent=Stopování a pach\nTactical Deployment=Taktické nasazení\nVehicle & Equipment=Vozidlo a výbava\nCare & Medical=Péče a zdraví\nTraining & Certifications=Výcvik a certifikace\nDeploy / Dismiss=Nasadit / odvolat\nBack to Command Categories=Zpět na kategorie\nIdentity & Appearance=Identita a vzhled\nHUD & Display=HUD a zobrazení\nKennel Location Editor=Editor umístění kotců\nVehicle Seat Configuration=Nastavení sedadla\nProfile, Health & Certifications=Profil, zdraví a certifikace\nLanguage=Jazyk\nAppearance=Vzhled\nEdit name=Upravit jméno\nBreed/model=Plemeno/model\nSkin/coat=Kůže/srst\nEquipment/vest=Výbava/vesta\nVest texture=Textura vesty\nBack to K9 Profile=Zpět na profil K9\nKennel Locations=Umístění kotců\nSave for this vehicle model=Uložit pro tento model\nReset to global defaults=Obnovit globální výchozí";
        private const string MenuIt="Commands=Comandi\nPartner Control=Controllo del compagno\nSearch & Detection=Ricerca e rilevamento\nTracking & Scent=Traccia e odore\nTactical Deployment=Impiego tattico\nVehicle & Equipment=Veicolo e attrezzatura\nCare & Medical=Cura e medicina\nTraining & Certifications=Addestramento e certificazioni\nDeploy / Dismiss=Schiera / congeda\nBack to Command Categories=Torna alle categorie\nIdentity & Appearance=Identità e aspetto\nHUD & Display=HUD e schermo\nKennel Location Editor=Editor posizione canili\nVehicle Seat Configuration=Configurazione sedile\nProfile, Health & Certifications=Profilo, salute e certificazioni\nLanguage=Lingua\nAppearance=Aspetto\nEdit name=Modifica nome\nBreed/model=Razza/modello\nSkin/coat=Pelle/mantello\nEquipment/vest=Equipaggiamento/gilet\nVest texture=Texture del gilet\nBack to K9 Profile=Torna al profilo K9\nKennel Locations=Posizioni canili\nSave for this vehicle model=Salva per questo veicolo\nReset to global defaults=Ripristina valori globali";
        private const string MenuJa="Commands=コマンド\nPartner Control=パートナー操作\nSearch & Detection=捜索と探知\nTracking & Scent=追跡と臭気\nTactical Deployment=戦術展開\nVehicle & Equipment=車両と装備\nCare & Medical=ケアと医療\nTraining & Certifications=訓練と資格\nDeploy / Dismiss=出動 / 収納\nBack to Command Categories=コマンド分類に戻る\nIdentity & Appearance=情報と外観\nHUD & Display=HUDと表示\nKennel Location Editor=犬舎位置編集\nVehicle Seat Configuration=車両座席設定\nProfile, Health & Certifications=プロフィール、健康、資格\nLanguage=言語\nAppearance=外観\nEdit name=名前を編集\nBreed/model=犬種/モデル\nSkin/coat=スキン/毛色\nEquipment/vest=装備/ベスト\nVest texture=ベストのテクスチャ\nBack to K9 Profile=K9プロフィールに戻る\nKennel Locations=犬舎の場所\nSave for this vehicle model=この車種用に保存\nReset to global defaults=共通初期値に戻す";
        private const string MenuPl="Commands=Komendy\nPartner Control=Sterowanie partnerem\nSearch & Detection=Przeszukanie i wykrywanie\nTracking & Scent=Tropienie i zapach\nTactical Deployment=Działania taktyczne\nVehicle & Equipment=Pojazd i wyposażenie\nCare & Medical=Opieka i medycyna\nTraining & Certifications=Szkolenie i certyfikaty\nDeploy / Dismiss=Wypuść / odwołaj\nBack to Command Categories=Wróć do kategorii\nIdentity & Appearance=Tożsamość i wygląd\nHUD & Display=HUD i ekran\nKennel Location Editor=Edytor lokalizacji kojców\nVehicle Seat Configuration=Konfiguracja siedzenia\nProfile, Health & Certifications=Profil, zdrowie i certyfikaty\nLanguage=Język\nAppearance=Wygląd\nEdit name=Edytuj imię\nBreed/model=Rasa/model\nSkin/coat=Skóra/sierść\nEquipment/vest=Wyposażenie/kamizelka\nVest texture=Tekstura kamizelki\nBack to K9 Profile=Wróć do profilu K9\nKennel Locations=Lokalizacje kojców\nSave for this vehicle model=Zapisz dla tego pojazdu\nReset to global defaults=Przywróć ustawienia globalne";

        // Each first phrase is also the translated command-menu label. Additional
        // phrases are natural spoken alternatives accepted by the voice matcher.
        private const string CommandsEs="Follow=Seguir|sígueme\nHeel=Junto|al pie\nSit=Sentado|siéntate\nLieDown=Tumbado|échate\nStay=Quieto|quédate\nRecall=Ven|vuelve\nWhistleRecall=Silbido de regreso\nHandSignal=Señal de mano\nFetch=Busca la pelota|trae la pelota\nSearchArea=Busca en la zona\nSearchBuilding=Registra el edificio\nSearchVehicle=Registra el vehículo|busca en el coche\nSearchNarcotics=Busca narcóticos|busca drogas\nSearchExplosives=Busca explosivos|busca bombas\nSearchWeapons=Busca armas\nCollectScent=Recoge el olor\nTrack=Rastrea|sigue el olor\nFindTrail=Recupera el rastro\nK9Warning=Aviso K9\nApprehend=Detén al sospechoso|ataca\nHandoffArrest=Entrega del arresto\nRequestPerimeter=Solicita perímetro\nHoldPerimeter=Mantén el perímetro\nContainSuspect=Contén al sospechoso\nRequestTransport=Solicita transporte\nRequestMedical=Solicita ambulancia\nRequestBombSquad=Solicita artificieros\nDoorPop=Abre la puerta\nRelease=Suelta|déjalo\nGuard=Vigila\nBark=Ladra\nEnterVehicle=Entra al vehículo|sube al coche\nExitVehicle=Sal del vehículo|baja del coche\nPet=Acariciar|buen perro\nFeed=Dar comida|premio\nDrink=Dar agua\nRest=Descansa\nInspect=Revisar K9\nFirstAid=Primeros auxilios\nCarryK9=Cargar K9|recoge al perro\nVeterinaryCare=Cuidado veterinario\nRestock=Reponer equipo\nToggleLeash=Correa|poner la correa|quitar la correa\nToggleCamera=Cámara K9\nTraining=Entrenamiento básico\nTrainNarcotics=Entrenamiento de narcóticos\nTrainExplosives=Entrenamiento de explosivos\nTrainWeapons=Entrenamiento de armas\nSpawnDismiss=Desplegar K9|retirar K9";
        private const string CommandsFr="Follow=Suivre|suis-moi\nHeel=Au pied\nSit=Assis|assis-toi\nLieDown=Couché\nStay=Reste|pas bouger\nRecall=Reviens|viens ici\nWhistleRecall=Rappel au sifflet\nHandSignal=Signal de la main\nFetch=Rapporte|cherche la balle\nSearchArea=Fouille la zone\nSearchBuilding=Fouille le bâtiment\nSearchVehicle=Fouille le véhicule|cherche dans la voiture\nSearchNarcotics=Cherche les stupéfiants|cherche la drogue\nSearchExplosives=Cherche les explosifs|cherche la bombe\nSearchWeapons=Cherche les armes\nCollectScent=Prends l'odeur\nTrack=Piste|suis la piste\nFindTrail=Retrouve la piste\nK9Warning=Avertissement K9\nApprehend=Appréhende le suspect|attaque\nHandoffArrest=Transfert d'arrestation\nRequestPerimeter=Demande un périmètre\nHoldPerimeter=Tiens le périmètre\nContainSuspect=Contiens le suspect\nRequestTransport=Demande un transport\nRequestMedical=Demande les secours\nRequestBombSquad=Demande les démineurs\nDoorPop=Ouvre la porte\nRelease=Lâche|arrête\nGuard=Garde\nBark=Aboie\nEnterVehicle=Monte dans le véhicule\nExitVehicle=Sors du véhicule\nPet=Caresser|bon chien\nFeed=Nourrir|donne une friandise\nDrink=Donne de l'eau\nRest=Repose-toi\nInspect=Examiner K9\nFirstAid=Premiers secours\nCarryK9=Porter K9|ramasse le chien\nVeterinaryCare=Soins vétérinaires\nRestock=Réapprovisionner\nToggleLeash=Laisse|mets la laisse|enlève la laisse\nToggleCamera=Caméra K9\nTraining=Entraînement de base\nTrainNarcotics=Entraînement stupéfiants\nTrainExplosives=Entraînement explosifs\nTrainWeapons=Entraînement armes\nSpawnDismiss=Déploie K9|retire K9";
        private const string CommandsZh="Follow=跟随|跟着我\nHeel=靠腿\nSit=坐下\nLieDown=趴下\nStay=别动|待着\nRecall=回来|过来\nWhistleRecall=口哨召回\nHandSignal=手势指令\nFetch=取回来|拿球\nSearchArea=搜索区域\nSearchBuilding=搜索建筑\nSearchVehicle=搜索车辆\nSearchNarcotics=搜索毒品\nSearchExplosives=搜索爆炸物|搜索炸弹\nSearchWeapons=搜索武器\nCollectScent=采集气味\nTrack=追踪|跟踪气味\nFindTrail=重新找到踪迹\nK9Warning=警犬警告\nApprehend=抓住嫌疑人|攻击\nHandoffArrest=移交逮捕\nRequestPerimeter=请求封锁\nHoldPerimeter=守住封锁线\nContainSuspect=控制嫌疑人\nRequestTransport=请求押送\nRequestMedical=请求医疗\nRequestBombSquad=请求排爆组\nDoorPop=打开车门\nRelease=松开|停止\nGuard=警戒\nBark=叫\nEnterVehicle=上车\nExitVehicle=下车\nPet=抚摸|好狗\nFeed=喂食|给奖励\nDrink=给水\nRest=休息\nInspect=检查警犬\nFirstAid=急救\nCarryK9=抱起警犬|抱起狗\nVeterinaryCare=兽医护理\nRestock=补充装备\nToggleLeash=牵引绳|系上牵引绳|解开牵引绳\nToggleCamera=警犬摄像机\nTraining=基础训练\nTrainNarcotics=毒品训练\nTrainExplosives=爆炸物训练\nTrainWeapons=武器训练\nSpawnDismiss=部署警犬|收回警犬";
        private const string CommandsPt="Follow=Seguir|segue-me\nHeel=Junto\nSit=Senta|sentado\nLieDown=Deita\nStay=Fica|quieto\nRecall=Volta|vem aqui\nWhistleRecall=Retorno com assobio\nHandSignal=Sinal de mão\nFetch=Busca|traz a bola\nSearchArea=Procura na área\nSearchBuilding=Revista o prédio\nSearchVehicle=Revista o veículo\nSearchNarcotics=Procura narcóticos|procura drogas\nSearchExplosives=Procura explosivos|procura bomba\nSearchWeapons=Procura armas\nCollectScent=Recolhe o odor\nTrack=Rastreia|segue o cheiro\nFindTrail=Recupera a trilha\nK9Warning=Aviso K9\nApprehend=Captura o suspeito|ataca\nHandoffArrest=Transferir prisão\nRequestPerimeter=Solicita perímetro\nHoldPerimeter=Mantém o perímetro\nContainSuspect=Contém o suspeito\nRequestTransport=Solicita transporte\nRequestMedical=Solicita emergência médica\nRequestBombSquad=Solicita esquadrão antibombas\nDoorPop=Abre a porta\nRelease=Solta|para\nGuard=Guarda\nBark=Late\nEnterVehicle=Entra no veículo\nExitVehicle=Sai do veículo\nPet=Acariciar|bom cachorro\nFeed=Alimentar|dar petisco\nDrink=Dar água\nRest=Descansa\nInspect=Examinar K9\nFirstAid=Primeiros socorros\nCarryK9=Carregar K9|pega o cachorro\nVeterinaryCare=Cuidados veterinários\nRestock=Repor equipamento\nToggleLeash=Guia|coloca a guia|tira a guia\nToggleCamera=Câmera K9\nTraining=Treinamento básico\nTrainNarcotics=Treinamento de narcóticos\nTrainExplosives=Treinamento de explosivos\nTrainWeapons=Treinamento de armas\nSpawnDismiss=Mobiliza K9|dispensa K9";
        private const string CommandsRu="Follow=Следуй|за мной\nHeel=Рядом|к ноге\nSit=Сидеть\nLieDown=Лежать\nStay=Место|стой\nRecall=Ко мне|вернись\nWhistleRecall=Отзыв свистком\nHandSignal=Жест рукой\nFetch=Апорт|принеси мяч\nSearchArea=Ищи на территории\nSearchBuilding=Обыщи здание\nSearchVehicle=Обыщи машину\nSearchNarcotics=Ищи наркотики\nSearchExplosives=Ищи взрывчатку|ищи бомбу\nSearchWeapons=Ищи оружие\nCollectScent=Возьми запах\nTrack=След|ищи по запаху\nFindTrail=Найди след снова\nK9Warning=Предупреждение K9\nApprehend=Задержать подозреваемого|фас\nHandoffArrest=Передать задержание\nRequestPerimeter=Запросить оцепление\nHoldPerimeter=Держать периметр\nContainSuspect=Блокировать подозреваемого\nRequestTransport=Запросить транспорт\nRequestMedical=Вызвать скорую\nRequestBombSquad=Вызвать сапёров\nDoorPop=Открыть дверь\nRelease=Отпусти|фу\nGuard=Охраняй\nBark=Голос\nEnterVehicle=В машину\nExitVehicle=Из машины\nPet=Погладить|хороший пёс\nFeed=Кормить|дать лакомство\nDrink=Дать воды\nRest=Отдыхай\nInspect=Осмотреть K9\nFirstAid=Первая помощь\nCarryK9=Нести K9|поднять собаку\nVeterinaryCare=Ветеринарная помощь\nRestock=Пополнить снаряжение\nToggleLeash=Поводок|надеть поводок|снять поводок\nToggleCamera=Камера K9\nTraining=Основная тренировка\nTrainNarcotics=Тренировка по наркотикам\nTrainExplosives=Тренировка по взрывчатке\nTrainWeapons=Тренировка по оружию\nSpawnDismiss=Вывести K9|убрать K9";
        private const string CommandsTh="Follow=ตาม|ตามฉันมา\nHeel=ชิดข้าง\nSit=นั่ง\nLieDown=หมอบ\nStay=อยู่|อย่าขยับ\nRecall=กลับมา|มานี่\nWhistleRecall=เรียกกลับด้วยเสียงนกหวีด\nHandSignal=สัญญาณมือ\nFetch=คาบมา|เอาลูกบอลมา\nSearchArea=ค้นหาพื้นที่\nSearchBuilding=ค้นหาอาคาร\nSearchVehicle=ค้นหารถ\nSearchNarcotics=ค้นหายาเสพติด\nSearchExplosives=ค้นหาวัตถุระเบิด|ค้นหาระเบิด\nSearchWeapons=ค้นหาอาวุธ\nCollectScent=เก็บกลิ่น\nTrack=ติดตาม|ตามกลิ่น\nFindTrail=หากลิ่นอีกครั้ง\nK9Warning=คำเตือน K9\nApprehend=จับผู้ต้องสงสัย|โจมตี\nHandoffArrest=ส่งต่อการจับกุม\nRequestPerimeter=ขอกำลังปิดล้อม\nHoldPerimeter=รักษาแนวปิดล้อม\nContainSuspect=ควบคุมผู้ต้องสงสัย\nRequestTransport=ขอรถควบคุม\nRequestMedical=ขอหน่วยแพทย์\nRequestBombSquad=ขอหน่วยเก็บกู้ระเบิด\nDoorPop=เปิดประตู\nRelease=ปล่อย|หยุด\nGuard=เฝ้า\nBark=เห่า\nEnterVehicle=ขึ้นรถ\nExitVehicle=ลงรถ\nPet=ลูบ|เด็กดี\nFeed=ให้อาหาร|ให้ขนม\nDrink=ให้น้ำ\nRest=พัก\nInspect=ตรวจ K9\nFirstAid=ปฐมพยาบาล\nCarryK9=อุ้ม K9|อุ้มสุนัข\nVeterinaryCare=รักษาสัตวแพทย์\nRestock=เติมอุปกรณ์\nToggleLeash=สายจูง|ใส่สายจูง|ถอดสายจูง\nToggleCamera=กล้อง K9\nTraining=ฝึกพื้นฐาน\nTrainNarcotics=ฝึกค้นหายาเสพติด\nTrainExplosives=ฝึกค้นหาวัตถุระเบิด\nTrainWeapons=ฝึกค้นหาอาวุธ\nSpawnDismiss=นำ K9 ออก|เก็บ K9";
        private const string CommandsTr="Follow=Takip et|beni takip et\nHeel=Yanıma gel\nSit=Otur\nLieDown=Yat\nStay=Kal|kıpırdama\nRecall=Geri gel|buraya gel\nWhistleRecall=Islıkla çağır\nHandSignal=El işareti\nFetch=Getir|topu getir\nSearchArea=Alanı ara\nSearchBuilding=Binayı ara\nSearchVehicle=Aracı ara\nSearchNarcotics=Uyuşturucu ara\nSearchExplosives=Patlayıcı ara|bomba ara\nSearchWeapons=Silah ara\nCollectScent=Koku al\nTrack=İz sür|kokuyu takip et\nFindTrail=İzi yeniden bul\nK9Warning=K9 uyarısı\nApprehend=Şüpheliyi yakala|saldır\nHandoffArrest=Tutuklamayı devret\nRequestPerimeter=Çevre güvenliği iste\nHoldPerimeter=Çevreyi tut\nContainSuspect=Şüpheliyi çevrele\nRequestTransport=Nakil iste\nRequestMedical=Sağlık ekibi iste\nRequestBombSquad=Bomba imha iste\nDoorPop=Kapıyı aç\nRelease=Bırak|dur\nGuard=Koru\nBark=Havla\nEnterVehicle=Araca bin\nExitVehicle=Araçtan in\nPet=Sev|aferin\nFeed=Besle|ödül ver\nDrink=Su ver\nRest=Dinlen\nInspect=K9 kontrol et\nFirstAid=İlk yardım\nCarryK9=K9 taşı|köpeği kaldır\nVeterinaryCare=Veteriner bakımı\nRestock=Ekipmanı tamamla\nToggleLeash=Tasma|tasmayı tak|tasmayı çıkar\nToggleCamera=K9 kamerası\nTraining=Temel eğitim\nTrainNarcotics=Uyuşturucu eğitimi\nTrainExplosives=Patlayıcı eğitimi\nTrainWeapons=Silah eğitimi\nSpawnDismiss=K9 görevlendir|K9 geri gönder";
        private const string CommandsVi="Follow=Đi theo|theo tôi\nHeel=Đi sát\nSit=Ngồi\nLieDown=Nằm xuống\nStay=Ở yên|đừng di chuyển\nRecall=Quay lại|lại đây\nWhistleRecall=Gọi lại bằng còi\nHandSignal=Ra hiệu tay\nFetch=Nhặt về|lấy bóng\nSearchArea=Tìm khu vực\nSearchBuilding=Tìm trong tòa nhà\nSearchVehicle=Tìm trong xe\nSearchNarcotics=Tìm ma túy\nSearchExplosives=Tìm chất nổ|tìm bom\nSearchWeapons=Tìm vũ khí\nCollectScent=Lấy mẫu mùi\nTrack=Theo dấu|theo mùi\nFindTrail=Tìm lại dấu\nK9Warning=Cảnh báo K9\nApprehend=Bắt nghi phạm|tấn công\nHandoffArrest=Bàn giao bắt giữ\nRequestPerimeter=Yêu cầu vành đai\nHoldPerimeter=Giữ vành đai\nContainSuspect=Khống chế nghi phạm\nRequestTransport=Yêu cầu xe áp giải\nRequestMedical=Yêu cầu y tế\nRequestBombSquad=Yêu cầu đội bom\nDoorPop=Mở cửa\nRelease=Thả ra|dừng lại\nGuard=Canh gác\nBark=Sủa\nEnterVehicle=Lên xe\nExitVehicle=Xuống xe\nPet=Vuốt ve|chó ngoan\nFeed=Cho ăn|cho phần thưởng\nDrink=Cho uống nước\nRest=Nghỉ ngơi\nInspect=Kiểm tra K9\nFirstAid=Sơ cứu\nCarryK9=Bế K9|bế chó\nVeterinaryCare=Chăm sóc thú y\nRestock=Bổ sung thiết bị\nToggleLeash=Dây dắt|đeo dây dắt|tháo dây dắt\nToggleCamera=Camera K9\nTraining=Huấn luyện cơ bản\nTrainNarcotics=Huấn luyện ma túy\nTrainExplosives=Huấn luyện chất nổ\nTrainWeapons=Huấn luyện vũ khí\nSpawnDismiss=Triển khai K9|cho K9 nghỉ";
        private const string CommandsDe="Follow=Folgen|folge mir\nHeel=Bei Fuß\nSit=Sitz\nLieDown=Platz\nStay=Bleib\nRecall=Komm zurück|hierher\nWhistleRecall=Pfeifenrückruf\nHandSignal=Handzeichen\nFetch=Hol|bring den Ball\nSearchArea=Such das Gebiet ab\nSearchBuilding=Durchsuche das Gebäude\nSearchVehicle=Durchsuche das Fahrzeug\nSearchNarcotics=Suche Drogen\nSearchExplosives=Suche Sprengstoff|suche Bombe\nSearchWeapons=Suche Waffen\nCollectScent=Nimm die Witterung auf\nTrack=Spur suchen|folge der Fährte\nFindTrail=Fährte wiederfinden\nK9Warning=Diensthundwarnung\nApprehend=Fass den Verdächtigen|fass\nHandoffArrest=Festnahme übergeben\nRequestPerimeter=Sperrkreis anfordern\nHoldPerimeter=Sperrkreis halten\nContainSuspect=Verdächtigen eindämmen\nRequestTransport=Gefangenentransport anfordern\nRequestMedical=Rettungsdienst anfordern\nRequestBombSquad=Entschärfer anfordern\nDoorPop=Tür öffnen\nRelease=Aus|lass los\nGuard=Bewachen\nBark=Gib Laut\nEnterVehicle=Ins Fahrzeug\nExitVehicle=Aus dem Fahrzeug\nPet=Streicheln|braver Hund\nFeed=Füttern|Leckerli geben\nDrink=Wasser geben\nRest=Ausruhen\nInspect=K9 untersuchen\nFirstAid=Erste Hilfe\nCarryK9=K9 tragen|Hund aufheben\nVeterinaryCare=Tierärztliche Versorgung\nRestock=Ausrüstung auffüllen\nToggleLeash=Leine|Leine anlegen|Leine abnehmen\nToggleCamera=K9-Kamera\nTraining=Grundausbildung\nTrainNarcotics=Drogensuchtraining\nTrainExplosives=Sprengstofftraining\nTrainWeapons=Waffensuchtraining\nSpawnDismiss=K9 einsetzen|K9 zurückrufen";
        private const string CommandsCs="Follow=Následuj|za mnou\nHeel=K noze\nSit=Sedni\nLieDown=Lehni\nStay=Zůstaň\nRecall=Ke mně|vrať se\nWhistleRecall=Přivolání píšťalkou\nHandSignal=Signál rukou\nFetch=Aport|přines míček\nSearchArea=Prohledej oblast\nSearchBuilding=Prohledej budovu\nSearchVehicle=Prohledej vozidlo\nSearchNarcotics=Hledej drogy\nSearchExplosives=Hledej výbušniny|hledej bombu\nSearchWeapons=Hledej zbraně\nCollectScent=Načti pach\nTrack=Stopuj|sleduj pach\nFindTrail=Najdi stopu znovu\nK9Warning=Varování K9\nApprehend=Zadrž podezřelého|zaútoč\nHandoffArrest=Předat zatčení\nRequestPerimeter=Vyžádat perimetr\nHoldPerimeter=Držet perimetr\nContainSuspect=Zadržet podezřelého\nRequestTransport=Vyžádat převoz\nRequestMedical=Vyžádat záchranku\nRequestBombSquad=Vyžádat pyrotechniky\nDoorPop=Otevři dveře\nRelease=Pusť|dost\nGuard=Hlídej\nBark=Štěkej\nEnterVehicle=Do vozidla\nExitVehicle=Z vozidla\nPet=Pohladit|hodný pes\nFeed=Nakrmit|dát pamlsek\nDrink=Dát vodu\nRest=Odpočívej\nInspect=Prohlédnout K9\nFirstAid=První pomoc\nCarryK9=Nést K9|zvednout psa\nVeterinaryCare=Veterinární péče\nRestock=Doplnit výbavu\nToggleLeash=Vodítko|nasadit vodítko|sundat vodítko\nToggleCamera=Kamera K9\nTraining=Základní výcvik\nTrainNarcotics=Výcvik drog\nTrainExplosives=Výcvik výbušnin\nTrainWeapons=Výcvik zbraní\nSpawnDismiss=Nasadit K9|odvolat K9";
        private const string CommandsIt="Follow=Segui|seguimi\nHeel=Al piede\nSit=Seduto\nLieDown=Terra\nStay=Resta|fermo\nRecall=Torna|vieni qui\nWhistleRecall=Richiamo con fischio\nHandSignal=Segnale manuale\nFetch=Riporta|prendi la palla\nSearchArea=Cerca nell'area\nSearchBuilding=Perquisisci l'edificio\nSearchVehicle=Perquisisci il veicolo\nSearchNarcotics=Cerca stupefacenti|cerca droga\nSearchExplosives=Cerca esplosivi|cerca bomba\nSearchWeapons=Cerca armi\nCollectScent=Prendi l'odore\nTrack=Traccia|segui l'odore\nFindTrail=Ritrova la traccia\nK9Warning=Avviso K9\nApprehend=Ferma il sospetto|attacca\nHandoffArrest=Passa l'arresto\nRequestPerimeter=Richiedi perimetro\nHoldPerimeter=Mantieni il perimetro\nContainSuspect=Contieni il sospetto\nRequestTransport=Richiedi trasporto\nRequestMedical=Richiedi soccorso medico\nRequestBombSquad=Richiedi artificieri\nDoorPop=Apri la porta\nRelease=Lascia|fermo\nGuard=Sorveglia\nBark=Abbaia\nEnterVehicle=Entra nel veicolo\nExitVehicle=Esci dal veicolo\nPet=Accarezza|bravo cane\nFeed=Nutri|dai premio\nDrink=Dai acqua\nRest=Riposa\nInspect=Controlla K9\nFirstAid=Primo soccorso\nCarryK9=Trasporta K9|solleva il cane\nVeterinaryCare=Cure veterinarie\nRestock=Rifornisci attrezzatura\nToggleLeash=Guinzaglio|metti il guinzaglio|togli il guinzaglio\nToggleCamera=Telecamera K9\nTraining=Addestramento base\nTrainNarcotics=Addestramento stupefacenti\nTrainExplosives=Addestramento esplosivi\nTrainWeapons=Addestramento armi\nSpawnDismiss=Schiera K9|congeda K9";
        private const string CommandsJa="Follow=ついてこい|ついてきて\nHeel=ヒール|横につけ\nSit=お座り\nLieDown=伏せ\nStay=待て\nRecall=来い|戻れ\nWhistleRecall=笛で呼び戻す\nHandSignal=ハンドシグナル\nFetch=持ってこい|ボールを取れ\nSearchArea=周辺を捜索\nSearchBuilding=建物を捜索\nSearchVehicle=車両を捜索\nSearchNarcotics=薬物を捜索\nSearchExplosives=爆発物を捜索|爆弾を探せ\nSearchWeapons=武器を捜索\nCollectScent=臭いを取れ\nTrack=追跡|臭いを追え\nFindTrail=臭跡を再発見\nK9Warning=警察犬警告\nApprehend=容疑者を確保|攻撃\nHandoffArrest=逮捕引き継ぎ\nRequestPerimeter=包囲を要請\nHoldPerimeter=包囲を維持\nContainSuspect=容疑者を封じ込めろ\nRequestTransport=護送を要請\nRequestMedical=救急を要請\nRequestBombSquad=爆発物処理班を要請\nDoorPop=ドアを開けろ\nRelease=離せ|やめ\nGuard=警戒\nBark=吠えろ\nEnterVehicle=車に乗れ\nExitVehicle=車から降りろ\nPet=撫でる|いい子\nFeed=餌を与える|ご褒美\nDrink=水を与える\nRest=休め\nInspect=警察犬を確認\nFirstAid=応急処置\nCarryK9=警察犬を運ぶ|犬を抱く\nVeterinaryCare=獣医治療\nRestock=装備補充\nToggleLeash=リード|リードを付ける|リードを外す\nToggleCamera=警察犬カメラ\nTraining=基礎訓練\nTrainNarcotics=薬物探知訓練\nTrainExplosives=爆発物探知訓練\nTrainWeapons=武器探知訓練\nSpawnDismiss=警察犬を出す|警察犬を戻す";
        private const string CommandsPl="Follow=Podążaj|za mną\nHeel=Do nogi\nSit=Siad\nLieDown=Waruj\nStay=Zostań\nRecall=Do mnie|wróć\nWhistleRecall=Przywołanie gwizdkiem\nHandSignal=Sygnał ręką\nFetch=Aport|przynieś piłkę\nSearchArea=Przeszukaj teren\nSearchBuilding=Przeszukaj budynek\nSearchVehicle=Przeszukaj pojazd\nSearchNarcotics=Szukaj narkotyków\nSearchExplosives=Szukaj materiałów wybuchowych|szukaj bomby\nSearchWeapons=Szukaj broni\nCollectScent=Pobierz zapach\nTrack=Trop|idź za zapachem\nFindTrail=Odnajdź trop\nK9Warning=Ostrzeżenie K9\nApprehend=Zatrzymaj podejrzanego|atakuj\nHandoffArrest=Przekaż zatrzymanie\nRequestPerimeter=Wezwij kordon\nHoldPerimeter=Trzymaj kordon\nContainSuspect=Powstrzymaj podejrzanego\nRequestTransport=Wezwij transport\nRequestMedical=Wezwij pogotowie\nRequestBombSquad=Wezwij saperów\nDoorPop=Otwórz drzwi\nRelease=Puść|zostaw\nGuard=Pilnuj\nBark=Daj głos\nEnterVehicle=Do pojazdu\nExitVehicle=Z pojazdu\nPet=Pogłaszcz|dobry pies\nFeed=Nakarm|daj smakołyk\nDrink=Daj wodę\nRest=Odpocznij\nInspect=Sprawdź K9\nFirstAid=Pierwsza pomoc\nCarryK9=Nieś K9|podnieś psa\nVeterinaryCare=Opieka weterynaryjna\nRestock=Uzupełnij wyposażenie\nToggleLeash=Smycz|załóż smycz|zdejmij smycz\nToggleCamera=Kamera K9\nTraining=Szkolenie podstawowe\nTrainNarcotics=Szkolenie narkotykowe\nTrainExplosives=Szkolenie materiałów wybuchowych\nTrainWeapons=Szkolenie broni\nSpawnDismiss=Wypuść K9|odwołaj K9";
    }
}

